version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: skincheck_db
      MYSQL_USER: skincheck_user
      MYSQL_PASSWORD: skincheck_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: skincheck_user
      MYSQL_PASSWORD: skincheck_password
      MYSQL_DATABASE: skincheck_db
      SECRET_KEY: your-flask-secret-key-change-in-production
      JWT_SECRET_KEY: your-jwt-secret-key-change-in-production
      FLASK_ENV: production
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
    restart: unless-stopped

volumes:
  mysql_data: